/**
 * Auto-generated by generate-ambassador-codes.js
 * Generated at: 2026-03-28T18:05:32.258Z
 *
 * DO NOT EDIT MANUALLY. DO NOT REGENERATE.
 * These codes have been distributed to ambassadors.
 */

export const AMBASSADOR_REF_MAP = {
  'd26-iitb-a823': 'IIT Bombay',
  'd26-iitk-e827': 'IIT Kharagpur',
  'd26-iitd-62a6': 'IIT Delhi',
  'd26-iitm-0fbd': 'IIT Madras',
  'd26-iitr-3553': 'IIT Roorkee',
  'd26-iitg-8fd0': 'IIT Guwahati',
  'd26-iith-036f': 'IIT Hyderabad',
  'd26-iitk2-ac02': 'IIT Kanpur',
  'd26-bitsp-2d38': 'BITS Pilani',
  'd26-bitsg-0354': 'BITS Goa',
  'd26-bitsh-34c4': 'BITS Hyderabad',
  'd26-iisc-b6d3': 'IISc Bangalore',
  'd26-nitt-02b2': 'NIT Trichy',
  'd26-nitw-2d88': 'NIT Warangal',
  'd26-nitk-0e9e': 'NIT Surathkal',
  'd26-nitp-6de2': 'NIT Patna',
  'd26-nits-98bc': 'NIT Srinagar',
  'd26-iiith-df70': 'IIIT Hyderabad',
  'd26-nsut-ae8b': 'NSUT Delhi',
  'd26-dtu-a3cf': 'DTU Delhi',
  'd26-tsec-7de2': 'TSEC Mumbai',
  'd26-ict-bdfd': 'ICT Mumbai',
  'd26-vit-eebd': 'VIT Vellore',
  'd26-mahe-a1c9': 'Manipal',
  'd26-iitbhu-82c6': 'IIT BHU',
  'd26-nitbpl-5804': 'NIT Bhopal',
  'd26-iitp-c304': 'IIT Patna',
  'd26-iitp-40a4': 'IIT Patna (Ambassador 2)',
  'd26-iitmandi-867b': 'IIT Mandi',
  'd26-iitgn-dcff': 'IIT Gandhinagar',
};

export const AMBASSADOR_LINKS = {
  'IIT Bombay': 'amsderive.in?ref=d26-iitb-a823',
  'IIT Kharagpur': 'amsderive.in?ref=d26-iitk-e827',
  'IIT Delhi': 'amsderive.in?ref=d26-iitd-62a6',
  'IIT Madras': 'amsderive.in?ref=d26-iitm-0fbd',
  'IIT Roorkee': 'amsderive.in?ref=d26-iitr-3553',
  'IIT Guwahati': 'amsderive.in?ref=d26-iitg-8fd0',
  'IIT Hyderabad': 'amsderive.in?ref=d26-iith-036f',
  'IIT Kanpur': 'amsderive.in?ref=d26-iitk2-ac02',
  'BITS Pilani': 'amsderive.in?ref=d26-bitsp-2d38',
  'BITS Goa': 'amsderive.in?ref=d26-bitsg-0354',
  'BITS Hyderabad': 'amsderive.in?ref=d26-bitsh-34c4',
  'IISc Bangalore': 'amsderive.in?ref=d26-iisc-b6d3',
  'NIT Trichy': 'amsderive.in?ref=d26-nitt-02b2',
  'NIT Warangal': 'amsderive.in?ref=d26-nitw-2d88',
  'NIT Surathkal': 'amsderive.in?ref=d26-nitk-0e9e',
  'NIT Patna': 'amsderive.in?ref=d26-nitp-6de2',
  'NIT Srinagar': 'amsderive.in?ref=d26-nits-98bc',
  'IIIT Hyderabad': 'amsderive.in?ref=d26-iiith-df70',
  'NSUT Delhi': 'amsderive.in?ref=d26-nsut-ae8b',
  'DTU Delhi': 'amsderive.in?ref=d26-dtu-a3cf',
  'TSEC Mumbai': 'amsderive.in?ref=d26-tsec-7de2',
  'ICT Mumbai': 'amsderive.in?ref=d26-ict-bdfd',
  'VIT Vellore': 'amsderive.in?ref=d26-vit-eebd',
  'Manipal': 'amsderive.in?ref=d26-mahe-a1c9',
  'IIT BHU': 'amsderive.in?ref=d26-iitbhu-82c6',
  'NIT Bhopal': 'amsderive.in?ref=d26-nitbpl-5804',
  'IIT Patna': 'amsderive.in?ref=d26-iitp-c304',
  'IIT Patna (Ambassador 2)': 'amsderive.in?ref=d26-iitp-40a4',
  'IIT Mandi': 'amsderive.in?ref=d26-iitmandi-867b',
  'IIT Gandhinagar': 'amsderive.in?ref=d26-iitgn-dcff',
};

export const PENDING_AMBASSADORS = [];
